# Generated by Django 4.2.4 on 2023-08-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='phone_no',
            field=models.CharField(max_length=20),
        ),
    ]
