# Generated by Django 4.2.4 on 2023-08-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_record_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='zipcode',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
