# Generated by Django 4.2.4 on 2023-08-27 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_record_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='profile_image',
        ),
    ]
