# Generated by Django 4.2.4 on 2023-08-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_record_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
