# Generated by Django 4.2.4 on 2023-08-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_record_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
