# Generated by Django 4.2.4 on 2023-09-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_record_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='profile_pic',
            field=models.ImageField(default='woman2.png', max_length=300, null=True, upload_to='images/'),
        ),
    ]
